version: 1
services:
  - type: web
    name: fall_website
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # Đảm bảo rằng lệnh này chính xác
    port: 5000  # Thường là 5000 cho Flask, nhưng hãy kiểm tra lại mã của bạn xem cổng nào đang được sử dụng
