services:
  - type: web
    name: fall_website  # Thay đổi tên dịch vụ của bạn tại đây
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app --bind 0.0.0.0:5000"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000  # Đảm bảo PORT được thiết lập
